name: Ubuntu Workflow
on: [push]

jobs:
  main:
    name: test networking on ubuntu
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: build
        run: make build

      - name: run
        run: make run