name: MacOS Workflow
on: [push]

jobs:
  main:
    name: test networking on macos
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: build
        run: make build

      - name: run
        run: make run